# Site settings
title: DevTools
email: salam@araye.net
description: > # this means to ignore newlines until "baseurl:"
 List of useful and time savig tools for developers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
encoding: utf-8

# Build settings
markdown: kramdown
highlighter: rouge

